-- MySQL Script generated by MySQL Workbench
-- Tue Nov 30 13:53:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MLD_ProjetC#
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MLD_ProjetC#
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MLD_ProjetC#` DEFAULT CHARACTER SET utf8 ;
USE `MLD_ProjetC#` ;

-- -----------------------------------------------------
-- Table `MLD_ProjetC#`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MLD_ProjetC#`.`Users` ;

CREATE TABLE IF NOT EXISTS `MLD_ProjetC#`.`Users` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `creationDate` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `userType` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueUsers` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MLD_ProjetC#`.`Pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MLD_ProjetC#`.`Pictures` ;

CREATE TABLE IF NOT EXISTS `MLD_ProjetC#`.`Pictures` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `size` INT NOT NULL,
  `dimension` VARCHAR(45) NOT NULL,
  `imageFormat` VARCHAR(4) NOT NULL,
  `tag` VARCHAR(45) NOT NULL,
  `releaseDate` DATETIME NOT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pictures_Users1_idx` (`Users_id` ASC) INVISIBLE,
  INDEX `UniquePictures` (`name` ASC, `size` ASC, `dimension` ASC, `Users_id` ASC, `imageFormat` ASC) VISIBLE,
  CONSTRAINT `fk_Pictures_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `MLD_ProjetC#`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MLD_ProjetC#`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MLD_ProjetC#`.`table1` ;

CREATE TABLE IF NOT EXISTS `MLD_ProjetC#`.`table1` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `table1col` VARCHAR(45) NULL,
  `table1col1` VARCHAR(45) NULL,
  `table1col2` VARCHAR(45) NULL,
  `table1col3` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MLD_ProjetC#`.`Users_has_Pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MLD_ProjetC#`.`Users_has_Pictures` ;

CREATE TABLE IF NOT EXISTS `MLD_ProjetC#`.`Users_has_Pictures` (
  `Users_id` INT NOT NULL,
  `Pictures_id` INT NOT NULL,
  PRIMARY KEY (`Users_id`, `Pictures_id`),
  INDEX `fk_Users_has_Pictures_Pictures1_idx` (`Pictures_id` ASC) VISIBLE,
  INDEX `fk_Users_has_Pictures_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Pictures_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `MLD_ProjetC#`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Pictures_Pictures1`
    FOREIGN KEY (`Pictures_id`)
    REFERENCES `MLD_ProjetC#`.`Pictures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `MLD_ProjetC#` ;

-- -----------------------------------------------------
-- Placeholder table for view `MLD_ProjetC#`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MLD_ProjetC#`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `MLD_ProjetC#`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MLD_ProjetC#`.`view1`;
DROP VIEW IF EXISTS `MLD_ProjetC#`.`view1` ;
USE `MLD_ProjetC#`;
CREATE  OR REPLACE VIEW `view1` AS
juhuj;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
