-- MySQL Script generated by MySQL Workbench
-- Fri Jan 14 09:16:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Terres
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Terres
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Terres` DEFAULT CHARACTER SET utf8 ;
USE `Terres` ;

-- -----------------------------------------------------
-- Table `Terres`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Terres`.`Users` ;

CREATE TABLE IF NOT EXISTS `Terres`.`Users` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `userType` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueUsers` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Terres`.`Pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Terres`.`Pictures` ;

CREATE TABLE IF NOT EXISTS `Terres`.`Pictures` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `size` INT NOT NULL,
  `accessPath`VARCHAR(90) NOT NULL,
  `imageFormat` VARCHAR(5) NOT NULL,
  `tag` VARCHAR(45) NOT NULL,
  `releaseDate` DATETIME NOT NULL,
  `Deleted` INT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pictures_Users1_idx` (`Users_id` ASC) INVISIBLE,
  INDEX `UniquePictures` (`name` ASC, `size` ASC, `dimension` ASC, `Users_id` ASC, `imageFormat` ASC) VISIBLE,
  CONSTRAINT `fk_Pictures_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `Terres`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Terres` ;

-- -----------------------------------------------------
-- Placeholder table for view `Terres`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terres`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `Terres`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Terres`.`view1`;
DROP VIEW IF EXISTS `Terres`.`view1` ;
USE `Terres`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
